### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by jackbrown1993** [jackbrown1993/Jacuzzi-RS485#19]
```
New data as of 21-11-2022 22:58:23
Set Temp: 40
Current Temp: 40

New data as of 21-11-2022 22:59:23
Set Temp: 40
Current Temp: 40

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<JacuzziRS485.listen() done, defined at /app/jacuzziRS485.py:588> exception=KeyError(80)>
Traceback (most recent call last):
  File "/app/jacuzziRS485.py", line 613, in listen
    await self.parse_C4status_update(data)
  File "/app/jacuzziRS485.py", line 393, in parse_C4status_update
    self.curtemp = temp_convert[data[3]]
                   ~~~~~~~~~~~~^^^^^^^^^
KeyError: 80
MQTT message received on topic: homie/hot_tub/J335/set_temperature/set with value: 20
MQTT message received on topic: homie/hot_tub/J335/set_temperature/set with value: 20
```

**Comment by jackbrown1993** [comment]
The hot tub must of returned value 40, for current_temp field. We currently don't have a mapping for this value in our temp_covert array.

The pattern the values appear to follow is:

Value 1 = x
Value 2 = x-1
Value 3 =  x+3
Value 4 = x+2

Then repeat.

Based on this, I can assume that a value of 40 is a temperature of 40.5C, although the hot tub can't be set to heat above 40C, that doesn't meet the water heat can't reach that temperature. So I will push a fix with values up to 45C which should fix this issue.
